"""Keep the raw collector in both mods identical and independently stageable.

The strict api_audit.lua is a generated byte-for-byte copy of the solo probe.lua.
Edit the solo collector, copy its complete bytes, and run these checks before a
release. The strict mod must work with the solo mod disabled or absent in TF2.
"""
import hashlib
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from prototype.strict_sync import stage_probe as stage
from prototype.tests import test_stage_probe as stage_fixtures
from tools import build_probe_package as package


ROOT = Path(__file__).resolve().parents[2]


class StrictApiAuditResourceTests(unittest.TestCase):
    def copies(self, root, solo=b"return {}\n", strict=b"return {}\n"):
        first = root / stage.SOLO_API_AUDIT
        second = root / "prototype/mod" / stage.MOD / stage.API_AUDIT
        for path, data in ((first, solo), (second, strict)):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        return first, second

    def fixture(self):
        case = stage_fixtures.StageTests(methodName="runTest")
        case.setUp()
        self.addCleanup(case.doCleanups)
        return case

    def test_repository_collector_copy_is_byte_identical(self):
        source = (ROOT / stage.SOLO_API_AUDIT).read_bytes()
        copied = (ROOT / "prototype/mod" / stage.MOD / stage.API_AUDIT).read_bytes()
        self.assertTrue(source)
        self.assertEqual(copied, source)
        self.assertEqual(stage.verify_api_audit_copy(ROOT), hashlib.sha256(source).hexdigest())
        self.assertIn(stage.API_AUDIT, stage.REQUIRED_MOD_FILES)

    def test_package_copy_check_rejects_drift_empty_missing_and_oversized_collectors(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            first, second = self.copies(root)
            expected = hashlib.sha256(first.read_bytes()).hexdigest()
            self.assertEqual(stage.verify_api_audit_copy(root), expected)
            second.write_bytes(b"return {different=true}\n")
            with self.assertRaisesRegex(stage.StageError, "drift"):
                stage.verify_api_audit_copy(root)
            first.write_bytes(b"")
            with self.assertRaisesRegex(stage.StageError, "empty"):
                stage.verify_api_audit_copy(root)
            first.write_bytes(b"a" * (1024 * 1024 + 1))
            with self.assertRaisesRegex(stage.StageError, "oversized"):
                stage.verify_api_audit_copy(root)
            first.unlink()
            with self.assertRaisesRegex(stage.StageError, "Missing"):
                stage.verify_api_audit_copy(root)

    def test_public_package_build_rejects_drift_before_freezing_or_creating_outputs(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self.copies(root, strict=b"outdated copy")
            with patch.object(package, "ROOT", root), patch.object(package.subprocess, "run") as freeze:
                with self.assertRaisesRegex(stage.StageError, "drift"):
                    package.build(stamp="must-not-build", save=root / "private.sav")
                freeze.assert_not_called()
            self.assertFalse((root / "dist").exists())
            self.assertFalse((root / "build").exists())

    def test_build_staging_contains_own_collector_without_any_solo_mod_resources(self):
        case = self.fixture()
        collector = (ROOT / stage.SOLO_API_AUDIT).read_bytes()
        strict_source = case.root / "prototype/mod" / stage.MOD / stage.API_AUDIT
        strict_source.write_bytes(collector)
        for name in stage.REQUIRED_BUILD_FILES:
            path = case.root / "prototype/mod" / stage.MOD / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(b"-- isolated build fixture\nreturn {}\n")
        self.assertFalse((case.root / stage.SOLO_API_AUDIT).exists())
        original_game = stage_fixtures._files(case.game)
        result = case.prepare("independent", profile="build_v2")
        output, session = Path(result["output"]), Path(result["session"])
        copied = output / "game/mods" / stage.MOD / stage.API_AUDIT
        self.assertEqual(copied.read_bytes(), collector)
        self.assertFalse((output / "game/mods/tf2_api_audit_1").exists())
        self.assertEqual(stage_fixtures._files(case.game), original_game)
        manifest = json.loads((session / "probe_manifest.json").read_text("utf-8"))
        expected = hashlib.sha256(collector).hexdigest()
        self.assertEqual(manifest["prototype_files"]["mod/" + stage.API_AUDIT], expected)
        payload = json.loads((session / "probe_payload.json").read_text("utf-8"))
        self.assertEqual(payload["files"][f"mods/{stage.MOD}/{stage.API_AUDIT}"], expected)

    def test_missing_strict_collector_blocks_staging_before_creating_output(self):
        case = self.fixture()
        (case.root / "prototype/mod" / stage.MOD / stage.API_AUDIT).unlink()
        with self.assertRaisesRegex(stage.StageError, "incomplete"):
            case.prepare("missing-collector")
        self.assertFalse((case.base / "missing-collector-session").exists())
        self.assertFalse((case.base / "missing-collector-output").exists())

    def test_collector_changes_are_bound_into_shared_manifest(self):
        case = self.fixture()
        first = case.prepare("before")
        collector = case.root / "prototype/mod" / stage.MOD / stage.API_AUDIT
        collector.write_bytes(collector.read_bytes() + b"-- changed collector\n")
        second = case.prepare("after")
        self.assertNotEqual(first["manifest_digest"], second["manifest_digest"])


if __name__ == "__main__":
    unittest.main()
